version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/emscripten/Dockerfile
    tty: true
    volumes:
      - ./Boxedwine:/Boxedwine
      - ./wine:/wine
    working_dir: /
    command: |
      /bin/bash -c '
       export PATH=$PATH:/emsdk/emscripten:/usr/bin/ &&
       source "/emsdk/emsdk_env.sh" &&
       cd / &&
       cd Boxedwine/project/emscripten/ &&
       bash buildjs.sh"
      '
  wine:
    build:
      context: .
      dockerfile: dockerfiles/wine/Dockerfile
    tty: true
    platform: linux/i386
    user: "1001:123"
    volumes:
      - ./Boxedwine:/Boxedwine
      - ./wine:/wine
    working_dir: /
    command: |
      /bin/bash -c '
        export VERSION=3.0 &&
        cd /Boxedwine/tools/buildWine &&
        bash buildAll.sh
      '
